services:
  db:
    image: postgres:16.3-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
#  mongo:
#    image: mongo:latest
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
#      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
#    volumes:
#      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
#  api:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8000:8080"
#    env_file:
#      - .env
#    depends_on:
#      - db
volumes:
  db_data: